### ISSUE TITLE
cms-bot does not reconginze the change in PR if old commit is pushed

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cms-bot#1038]
Currently cms-bot rely on latest commit timestamp for setting signatures and running tests. If someone force push a past commit to a PR then cms-bot does not reset signatures. 

One option to avoid this is to make use of PR request pushed_at timestamp.

**Comment by Dr15Jones** [comment]
assign core

**Comment by smuzaffar** [comment]
bot now uses commit statuses to keep track of test results. This issue can be closed now
