### ISSUE TITLE
Remove mention of AFS from release build messages

### ISSUE THREAD

**Issue by kpedro88** [cms-sw/cms-bot#1090]
We probably don't need to see the message "CERN AFS installation skipped for slc7_amd64_gcc630 as no CMSSW releases are now deployed on AFS." every time we build a release.

The bot workflow could probably be simplified somewhat with this message removed, but I am not 100% sure of the details of where to remove everything related to it.

**Comment by smuzaffar** [comment]
https://github.com/cms-sw/cms-bot/pull/1096 should remove the AFS deploy message. I keep the message around as in future we will need it for CVMFS installation.
