### ISSUE TITLE
Apply categories_map to cms-data

### ISSUE THREAD

**Issue by kpedro88** [cms-sw/cms-bot#1094]
The repositories in cms-data correspond to packages in cmssw. The same L2s from categories.py and category_map.py should be automatically assigned to review cms-data PRs.

**Comment by smuzaffar** [comment]
@kpedro88 , thanks for opening the issue. It is work in progress. We want to setup automatic testing of cms-data and cms-externals PRs via bot too. Once that is setup then we will teach the bot to assign L2s for cms-data too.

**Comment by smuzaffar** [comment]
This is now done. cmsbot now assign categories to cms-data and also can test all cms repositories using `please test` and `please test with....` commands
