### ISSUE TITLE
"please close" for cmssw repo

### ISSUE THREAD

**Issue by kpedro88** [cms-sw/cms-bot#1107]
I noticed that https://github.com/cms-sw/cms-bot/blob/master/cmsdist_merge_permissions.py has an option "please close" to close a cmsdist PR. Could this be added for L1s/L2s to close CMSSW PRs as well?

**Comment by smuzaffar** [comment]
@kpedro88, cmsdist_merge_permissions.py is for cmsdist `comp`  developers so that they can merge/close cmsdist PR released to cmsdist comp_* branches.

But if we want this feature for cmssw then we can add 'please close' command to cms-bot

**Comment by kpedro88** [comment]
Yes, that is what I meant.

**Comment by smuzaffar** [comment]
cms-bot now recognize 'please close' command from L1/L2 and release managers
http://cms-sw.github.io/cms-bot-cmssw-cmds.html

**Comment by fabiocos** [comment]
@smuzaffar this is additional on top of the native GitHub button, whose functionality is restricted, am I correct?

**Comment by smuzaffar** [comment]
yes, "Close" button is only visible to those who have write/admin permission of the repo. This will allow L2's to also close PRs instead of waiting on one of administrators.
