### ISSUE TITLE
Batch download of test outputs

### ISSUE THREAD

**Issue by schneiml** [cms-sw/cms-bot#1110]
Asking here for lack of a better forum: Is there a good way to download the `runTheMatrix` outputs from e.g. here?
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-26232/33881/runTheMatrix-results/

One would think that `curl` + `cern-get-sso-cookie` does the trick, but I can't get it to work on this page. Are there other options (URL inside CERN without SSO, or SSH to the machine, or some network file system?) to access these files?

**Comment by kpedro88** [comment]
`cern-get-sso-cookie` is supposed to work, but I have found it to be very inconsistent. Unfortunately I don't know of a better solution, besides e.g. using a browser plugin.

**Comment by smuzaffar** [comment]
The following works for me but I do not know how to download the directory. 

```
cern-get-sso-cookie -o cook --url https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-26352/33990/runTheMatrix-results/
curl -L -s -k -b cook https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-26352/33990/runTheMatrix-results/matrixTests.log
```

**Comment by schneiml** [comment]
Thanks @smuzaffar, that indeed works. One of the many curl options there must make the difference. Getting all the files is easy then (adjust regexp's to whatever you care about):
```
#!/bin/bash
cern-get-sso-cookie -o cook --url $1
 for d in $(curl -L -s -k -b cook $1 | grep -oE '"[0-9]+*.[0-9]+_[^"]*"' | tr -d '"'); do
   for f in $(curl -L -s -k -b cook "$1/$d" | grep -oE '"DQM.*.root"' | tr -d '"'); do
      (mkdir -p $d; cd $d; curl -O -L -s -k -b ../cook $1/$d/$f )
   done
done
```
