### ISSUE TITLE
Run TimeMemorySummary.py in PR tests

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cms-bot#1111]
Recent discussions about performance changes pointed to a usefulness of simple time and memory evaluation even in PR-like tests. Of course the timing information cannot be taken as a serious measurement of performances (dependent on machine and its load) but it could help in noticing large changes. The ```--customise Validation/Performance/TimeMemorySummary.py``` option is already used in the IB, any specific reason not to activate it also in PR tests? The only drawback I see is that it will make log files definitely longer...

**Comment by kpedro88** [comment]
Maybe we could make a version of it that only prints the summary? The per-event info makes the logs huge and hard to read, and I usually don't find it very useful.

**Comment by kpedro88** [comment]
Ah, that is the summary version, distinct from `TimeMemoryInfo`.

**Comment by fabiocos** [comment]
We are not printing Time info per event, just memory jumps when the happen....
Still the trigger output summary is huge when written (and timing detail as well)

**Comment by fabiocos** [comment]
@smuzaffar in case, looking at the bot code, in particular https://github.com/cms-sw/cms-bot/blob/master/run-pr-tests#L640 this update would men adding to EXTRA_MATRIX_ARGS ```--command "--customise Validation/Performance/TimeMemorySummary.py"``` right?

**Comment by smuzaffar** [comment]
@fabiocos , yes that is the correct place. As it is available in all release cycles so we can just hard code it here https://github.com/cms-sw/cms-bot/blob/master/run-pr-tests#L640

**Comment by fabiocos** [comment]
@smuzaffar should we consider also https://github.com/cms-sw/cms-bot/blob/master/pr_testing/test_multiple_prs.sh#L836 ?

**Comment by smuzaffar** [comment]
yes that should be updated but I will ask @gudrutis to sync in other changes too. For now #1112 is good enough to go in.

**Comment by smuzaffar** [comment]
I have merged #1112 and @gudrutis is going to fix the test_multiple_prs to include the changes.
