### ISSUE TITLE
Is it possible to download baseline output files?

### ISSUE THREAD

**Issue by andrius-k** [cms-sw/cms-bot#1124]
Now that we know how to batch download files from the test results: [https://github.com/cms-sw/cms-bot/issues/1110](https://github.com/cms-sw/cms-bot/issues/1110), is there a way to download not only PR output but also the baseline files?

**Comment by kpedro88** [comment]
Go to the IB page: https://cmssdt.cern.ch/SDT/html/showIB.html
Click on "Comparison baseline" for the desired release
then follow the same procedure.

If you are starting from a PR test page, you can click the linked IB name under the "Tests Results" heading to go directly to that IB on the IB page.

**Comment by andrius-k** [comment]
@kpedro88 Perfect, thanks!
