### ISSUE TITLE
Missing DQM comparison report

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cms-bot#1134]
Since a couple of days at least the DQM comparison report is missing in the PR test output, with the message:

```
Not Found
The requested URL /SDT/@JENKINS_PREFIX@-artifacts/baseLineComparisons/CMSSW_10_6_X_2019-05-07-1100+607ffb/31550/ was not found on this server.
```

A problem was also previously reported about missing directories in the comparison of some workflows.

**Comment by fabiocos** [comment]
@smuzaffar @mrodozov for instance see in https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-607ffb/54/summary.html

**Comment by smuzaffar** [comment]
@gudrutis , this could be the side effect of new PR testing job.

**Comment by smuzaffar** [comment]
@fabiocos  , this is fixed now and already uploaded PR results are also fixed e.g check https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-607ffb/54/summary.html

**Comment by fabiocos** [comment]
@smuzaffar thanks, this now works, still the initial problem looks still there, see in https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_6_X_2019-05-07-1100+607ffb/31550/ for instance: for wf 136.8311 the comparison directory is missing, but this is part of the short matrix for which there is a baseline reference (https://cmssdt.cern.ch/SDT/jenkins-artifacts/ib-baseline-tests/CMSSW_10_6_X_2019-05-08-2300/slc7_amd64_gcc700/-GenuineIntel/matrix-results/136.8311_RunJetHT2017F_reminiaod+RunJetHT2017F_reminiaod+REMINIAOD_data2017+HARVEST2017_REMINIAOD_data2017/)

**Comment by smuzaffar** [comment]
Please see https://github.com/cms-sw/cms-bot/issues/964#issuecomment-395701108 , we only upload those wf which contain Skipped, Null or Failed

**Comment by fabiocos** [comment]
@smuzaffar and I was supporting this and it was requested by @slava77 :-) ... good memory refresh, thanks, it is not a bug but a feature
