### ISSUE TITLE
Create FWLite repo like Stitched

### ISSUE THREAD

**Issue by gartung** [cms-sw/cms-bot#1135]
This repo would hold only the sources needed to build FWLite/Fireworks. In addition it would hold the generated CMakeLists.txt files and Serialiazation.cc files from Condformat/*Object.

**Comment by Dr15Jones** [comment]
@gartung would this aid in making a sustainable Conda package?

**Comment by gartung** [comment]
Yes. I would make the source more "official"

**Comment by smuzaffar** [comment]
@gartung , I can create FWLite repo but you might not be able to use it as it is. I am using https://github.com/cms-sw/git_filter to filter packages and force push the changes to Stitched repo. Every time this is run it creates different commit hashes (that is why I need to force push). So if you would like to add CMake files on top of it then they will be overridden on next push.

**Comment by gartung** [comment]
I will not commit CMakeLists.txt once I have https://github.com/gartung/buildfile2cmake working fully.

**Comment by smuzaffar** [comment]
Then can't you use cms-sw/cmssw repo plus https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_11_0_X/gcc700/fwlite_build_set.file to get the FWLite sources?

**Comment by gartung** [comment]
So you are suggesting a spare checkout with fwlite_build_set.file as the contents of .git/info/sparse-checkout?

**Comment by gartung** [comment]
For conda builds a tagged version is preferred.  I will need to see if I can use a sparse checkout during the conda build. If I can make that work then I will close the issue.

**Comment by gartung** [comment]
Also sparse checkout does not address adding the generated serialization files.

**Comment by smuzaffar** [comment]
yes something like that. fwlite_build_set.file is not exactly in sparse-checkout format e.g. you might need to add `/` in front of each line

**Comment by smuzaffar** [comment]
serialization files you have to generate any way, they are not part of cmssw

**Comment by gartung** [comment]
Generating the serialization files on macOS is problematic. I would prefer to generate them on Linux and add them as source. 

I guess there will be no official source for the conda build.

**Comment by smuzaffar** [comment]
If you need a source repo for conda then we can create an empty cmssw/FWLite repo where you can push sources from linux. You can start with cmssw tag, sparse checkout fwlite packages, generate serialization and add cmake files and push those as tag to cms-sw/FWLite.

**Comment by gartung** [comment]
Ok. Please create  cmssw/FWLite repo and give me permissions to write to it.
