### ISSUE TITLE
Track PR signatures by label in cms-data

### ISSUE THREAD

**Issue by kpedro88** [cms-sw/cms-bot#1141]
Followup to #1094:

I keep track of pending pull requests in my category using this page:
https://github.com/cms-sw/cmssw/pulls?q=is%3Apr+is%3Aopen+label%3Aupgrade-pending

Now category signatures are required in cms-data, but there are currently 50 repos in that organization.

Is there some way (on our side or GitHub's side) to aggregate the status of PRs from all cms-data repos?

**Comment by smuzaffar** [comment]
@kpedro88 there is nothing from github itself for this. We might have to cook up something ourself.
@gudrutis , can we make use of https://github.com/cms-sw/cms-prs to somehow present this information?

**Comment by smuzaffar** [comment]
@kpedro88 , @gudrutis mentioned that one can use the github queries to see the PRs from different organizations e.g `is:pr archived:false org:cms-data org:cms-externals org:cms-sw is:open label:orp-pending`  is going to show all cms PRs from all our github orgs. 

https://github.com/pulls?utf8=%E2%9C%93&q=is%3Apr+archived%3Afalse+org%3Acms-data+org%3Acms-externals+org%3Acms-sw+is%3Aopen+label%3Aorp-pending+

You can then click on upgrade-pending label to see only PRs for upgrade category.

**Comment by kpedro88** [comment]
Excellent! I did not know about this view. Thanks @gudrutis
