### ISSUE TITLE
Problem with igprof in IBs

### ISSUE THREAD

**Issue by kpedro88** [cms-sw/cms-bot#1151]
I noticed there is no step3 profile for WF 136.731. The problem appears to be that the file name is too long (e.g. in https://cmssdt.cern.ch/SDT/jenkins-artifacts/igprof/CMSSW_11_0_X_2019-06-10-1100/slc7_amd64_gcc700/pp/136.731_RunSinglePh2016B+RunSinglePh2016B+HLTDR2_2016+RECODR2_2016reHLT_skimSinglePh_HIPM+HARVESTDR2/step3_RunSinglePh2016B+RunSinglePh2016B+HLTDR2_2016+RECODR2_2016reHLT_skimSinglePh_HIPM+HARVESTDR2.log):
```
sh: step3___RAW2DIGI,L1Reco,RECO,SKIM:SinglePhotonJetPlusHOFilter+EXOMONOPOLE,EI,PAT,ALCA:SiStripCalZeroBias+SiStripCalMinBias+TkAlMinBias+EcalESAlign,DQM:@standardDQM+@ExtraHLT+@miniAODDQM___None___auto:run2_data_relval___RECO,MINIAOD,DQMIO___performance___100_EndOfJob.gz: File name too long
```

**Comment by gudrutis** [comment]
This code fragment in CMSSW is responsible for generating filenames. I suggest using hashcode in such case. 
https://github.com/gudrutis/cmssw/commit/422e8fa3a6af40aac7b90146714061cab2b5e5f7
Let me know if you think we should keep some info in the filename or hash is enough, for example, "step3_234567".

**Comment by gudrutis** [comment]
Should be fixed by https://github.com/cms-sw/cmssw/pull/27338
