### ISSUE TITLE
Modules taking long time during test of cmsdist with big rebuilds

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cms-bot#1169]
In the test of cms-sw/cmsdist#5091 we have noticed some tests taking long time in some modules, this can be seen from the message issued now by

https://github.com/cms-sw/cmssw/blob/master/Validation/Performance/python/TimeMemoryJobReport.py#L12

This has been already observed in a ROOT rebuild test, and is not seen in the corresponding baseline IBs (although we do not have a systematic monitoring of it yet).
@slava77 suggests this could be related to how large rebuilds are done. @smuzaffar @mrodozov any idea with respect to this?

**Comment by mrodozov** [comment]
tests are not started (neither unit tests nor relvals) until the completion of the rebuild. If the assumption is such that a test run might interfere with compilation. @slava77 would you elaborate on that suggestion ?

**Comment by slava77** [comment]
- Are the execution of the tests  and the build  reading/writing to the same locally mounted disk? (imagine this is a network mount shared with other read/writes; I can see how lots of I/O leads to some transient "locks")
- Is anything else allowed to run on the same nodes? (imagine that for a long build something else sneaks in and overloads the node by the time the tests  start)

**Comment by davidlange6** [comment]
(essentially) all the hardware is virtual, right @mrodozov ? (so shared in practice)

**Comment by fabiocos** [comment]
we cannot use the measurements of time are rigorous benchmarks because even if the VM machine would be exclusively used for us, we have no control on the underlying bare metal, this was the conclusion from discussions with @smuzaffar

**Comment by fabiocos** [comment]
from this to exceeding 600 seconds in a second module the step is a biut longer, but it might depend on some particular spike in the hardware load?

**Comment by mrodozov** [comment]
when a test of type test-this-pull-request and others like building and IB is running nothing else is allowed to run , we limit that having single jenkins executor per machine, with few exceptions, and focus on what and how is running for utilising it.
Every build machine we have (and the dev machines btw) has its own disk attached to it with name like this:
cmsbuild31_vol_447 on /dev/vdb
for our 31 machine
which answers the question of having concurrent I/O operations.

> (essentially) all the hardware is virtual, right @mrodozov ? (so shared in practice)

well, it's dedicated to our needs so we can think of it as not shared. 
To conclude - no we are not sharing (at least not knowingly) any resource so running 
relvals *should* (but its obviously not) somehow predictable, and if we have any doubts  we have to check it. 
I'd say lets run 10 times the same (merged) PR one after another and check if this is consistent if it is - I'll go and see why in detail.

**Comment by smuzaffar** [comment]
As we now have dedicated VMs , so timings should not change much. Do we still see such long times ?

**Comment by fabiocos** [comment]
@smuzaffar I do not recall messages in the last period I have followed the integration, not sure whether @silviodonato has seen them in January

**Comment by smuzaffar** [comment]
I think the issue was the steal time on old shared VMs. We should not see such issues any more as now (for last 6 months) we have dedicated VMs (no CPU overcommit) and local SSD disk.

Closing it, please open a new one if needed
