### ISSUE TITLE
Persistent test settings

### ISSUE THREAD

**Issue by kpedro88** [cms-sw/cms-bot#1191]
A common source of churn in PR tests occurs when someone misses special settings that were used in a previous test, and then the tests must be restarted/repeated.

It would be useful to have some way to tell the bot that a certain workflow, external, etc. should always be used to test the PR. That way, if someone just writes "please test", the special settings will automatically be applied. The list of "permanent" special settings should probably be configured/stored separately from temporary settings that could still be specified in the "please test" command.

**Comment by smuzaffar** [comment]
Thanks @kpedro88 for opening the issue. This ison our to do list. @mrodozov is looking in to it. We are thinking of a special comment e.g.
```
test parameters/settings
pull_requests=#PR1,#PR2,cms-sw/cmsdist#PRn
workflows=534.0,540.0
release=CMSSW_11_0_DEVEL_X
architecture=slc7_amd64_gcc900
full_build=true|false
```

bot then can use the settings from the last such comment made by a user, who has rights to start tests. One can still override part of settinsg via `please test ....` comment

Is this sound reasonable?

**Comment by fabiocos** [comment]
@smuzaffar is the syntax of these extra settings flexible or rigid? I mean are all the fields always needed, or the default will be used unless specified otherwise? I guess the latter is what we want. 
What about possible changes of settings during the PR review? They will be always possible I guess...

**Comment by kpedro88** [comment]
@smuzaffar this looks reasonable to me, thanks

Maybe worthwhile to have separate items for CMSSW PRs vs external PRs?

It would also be nice to have an option for the bot to print all the specified test settings, in case they get updated piecemeal over the course of a long PR review.

**Comment by mrodozov** [comment]
@kpedro88 pls see https://github.com/cms-sw/cms-bot/pull/1234 and maybe close this.

**Comment by kpedro88** [comment]
@mrodozov can you provide some description of how the new functionality works (preferably in the cms-bot command documentation so it's clear to everyone)?

**Comment by smuzaffar** [comment]
@kpedro88 , there are still few issues with this thatis why I did not advertise or updates here. Basic documentation is available cms-bot commands page http://cms-sw.github.io/cms-bot-cmssw-cmds.html but we are still testing this feature.

**Comment by kpedro88** [comment]
Okay, since this is nominally in place, the issue can be closed. Thanks!
