### ISSUE TITLE
add ability to address/tag L2 area by category (without assigning a label to a PR)

### ISSUE THREAD

**Issue by slava77** [cms-sw/cms-bot#1335]
occasionally a direct message to people from a review category is needed.
Tagging is possible by assigning a label, which is not always appropriate and is also limited to L1/L2 roles.
A direct alternative is to reverse the list of github account names from the categories.py file.

Something like ```[@cmsbuild[, please]] notify reconstruction``` could resolve the issue.

**Comment by Dr15Jones** [comment]
I often find myself digging through the cms-bot categories.py file in order to do this exact thing. It would definitely be nice if the bot could handle it directly.

**Comment by Dr15Jones** [comment]
assign core

**Comment by makortel** [comment]
I'd like such a feature as well. While we're at it, other case where I go look for `categories_map.py` is to find which L2 area is responsible for a given package when assigning issues. It would help me if the bot could recognize something along `assign FWCore/Framework` to look all L2 areas assigned for `FWCore/Framework` and assign them (the exact syntax could be better than what I sketched here).

**Comment by smuzaffar** [comment]
@slava77 , if I understand correctly, this command basically adds members of a category as watcher of the PR ... right?

**Comment by smuzaffar** [comment]
@makortel , can't you use http://cms-sw.github.io/categories.html to find this mapping?

**Comment by makortel** [comment]
I could but I don't see how it would be different from `categories_map.py`. I mean, either way I need to search for all occurrences of the package, and then scroll upwards to find the L2 category (admittedly the `categories.html` is clearer to read). It's not really a big burden, but I wanted to mention it out loud in case something like that would be easy to implement.

**Comment by slava77** [comment]
> @slava77 , if I understand correctly, this command basically adds members of a category as watcher of the PR ... right?

yes, almost.

This does not resolve a similar case where pinging individual(s) from a category directly helps to get more attention.
Perhaps a similar syntax, in addition to updating the watcher list of the PR can also be used to post "dear [least of github names] your attention is needed for this PR in message [link or quote]" to be posted by the bot following a trigger message directed to the category.

**Comment by slava77** [comment]
> yes, almost.
> 
> This does not resolve a similar case

admittedly, that was a feature creep comment.
My initial submission implied only the watcher list update per PR or per issue.

**Comment by smuzaffar** [comment]
> I could but I don't see how it would be different from `categories_map.py`. I mean, either way I need to search for all occurrences of the package, and then scroll upwards to find the L2 category (admittedly the `categories.html` is clearer to read). It's not really a big burden, but I wanted to mention it out loud in case something like that would be easy to implement.

@makortel , many times due to a typo bot simply ignores the comment while user waits for hours to bot to recognize the comment. In case of package names there is more chances of typos :-)

**Comment by smuzaffar** [comment]
@slava77 , how about we create one team per category and you can do `ping @ category` so that github send notifications for the member of that team? Having github teams means less change of typos too

**Comment by slava77** [comment]
> @slava77 , how about we create one team per category and you can do `ping @ category` so that github send notifications for the member of that team? Having github teams means less change of typos too

this sounds good; 
I suppose that the pattern will be something like @cms-sw-core

**Comment by smuzaffar** [comment]
yes, the syntax will be `@ cms-sw/category-name`

**Comment by smuzaffar** [comment]
Github teams `@cms-sw/<category>-l2` are now available . Now one can use `@cms-sw/<category>-l2` in comment to ping the members of team.
