### ISSUE TITLE
compare file & product sizes

### ISSUE THREAD

**Issue by jpata** [cms-sw/cms-bot#1396]
Add file size comparison to the bot tests.

via Slava:
> there is a script that compares the list of branches in various files. So, it could be a good place to co-locate the calls
> https://twiki.cern.ch/twiki/bin/viewauth/CMS/RecoIntegration#Compare_output_products

(as a note to myself, or others)

**Comment by jpata** [comment]
related issue: https://github.com/cms-sw/cmssw/issues/31817

we can track this in the phase2 PU profiling test, just need to understand where to put this in the scripts

**Comment by jpata** [comment]
#1414 and #1413 were merged, thank you @gartung and @smuzaffar! I think this issue is solved and can be closed.

**Comment by smuzaffar** [comment]
thanks @jpata for this good work
