### ISSUE TITLE
restore commit ID in the PR tests

### ISSUE THREAD

**Issue by slava77** [cms-sw/cms-bot#1454]
after some recent updates commit info of the tested PR in the test summary (`Tested at: abcabc1`) was dropped.
This prevents appropriate matching with the code used for the tests.
Please restore the commit info or add other means to get the details of the test setup.

Initially posted in https://github.com/cms-sw/cmssw/pull/32291#issuecomment-747182750

**Comment by smuzaffar** [comment]
@slava77 , https://github.com/cms-sw/cms-bot/pull/1458 should include the commit id (e.g. see https://github.com/cms-sw/cms-bot/pull/1458#issuecomment-754688935 ). Is this good enough to close this issue?

**Comment by slava77** [comment]
> @slava77 , #1458 should include the commit id (e.g. see [#1458 (comment)](https://github.com/cms-sw/cms-bot/pull/1458#issuecomment-754688935) ). Is this good enough to close this issue?

looks good
Thank you.
