### ISSUE TITLE
run GPU workflows with the bot

### ISSUE THREAD

**Issue by jpata** [cms-sw/cms-bot#1455]
For the recent PRs cms-sw/cmssw#31719, cms-sw/cmssw#31720 etc, we have started to test the GPU workflows that are in the matrix on local GPU-enabled machines.

I'm making this issue to keep track of the status of `enable gpu` support for running GPU workflows in the matrix directly with jenkins.

**Comment by smuzaffar** [comment]
@jpata , bot is now able to run GPU tests as part of standard PR tests. Currently the GPU tests for PR are defined in  https://github.com/cms-sw/cms-bot/blob/master/cmssw-pr-test-config#L2 . I can also include `-w gpu` to run all gpu related relvals

**Comment by smuzaffar** [comment]
@jpata , can we close this or is there any thing which is still missing for gpu tests?

**Comment by jpata** [comment]
Thank you @smuzaffar, looks like it's good!
