### ISSUE TITLE
parse and monitor JobReport.xml

### ISSUE THREAD

**Issue by jpata** [cms-sw/cms-bot#1525]
The `JobReport*.xml` files that are produced in the matrix baseline as well as for the PR tests seem to contain a lot of useful performance information about the PR.

https://cmssdt.cern.ch/SDT/jenkins-artifacts/ib-baseline-tests/CMSSW_11_3_X_2021-03-26-1100/slc7_amd64_gcc900/-GenuineIntel/matrix-results/23234.0_TTbar_14TeV+2026D49+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal/JobReport3.xml

For example, there is PeakValueRss, the output file size, the list of all input and output branches. This could be used to monitor (and report on the PR test summary) in case there are big changes wrt. the baseline.

It could also be nice to include them in the outputs from the `enable profiling` run (cc @gartung).

**Comment by smuzaffar** [comment]
@jpata , for IBs we do parse the job reports and accumulate this in elastic search e.g. see this grafana page 
https://monit-grafana.cern.ch/d/bB9CsmHWz/cmssdt-ibmatrix?orgId=11&var-release=CMSSW_12_1_X&var-release_2=CMSSW_12_1_ROOT624_X&var-release_3=CMSSW_12_1_DEVEL_X&var-field=AvgEventTime&var-architecture=All&var-workflow=1.0&var-step=All

**Comment by jpata** [comment]
Thanks, I was wondering if it would make sense to also add to the bot report & `enable profiling` output.
