### ISSUE TITLE
Security Issue?

### ISSUE THREAD

**Issue by rovere** [cms-sw/cms-bot#1539]
Dear all,
the parsing that uses [this](https://github.com/cms-sw/cms-bot/blob/485b0316404a788416d5c953764deb21aa59b375/process_pr.py#L42) regular expression, assembled via [this code](https://github.com/cms-sw/cms-bot/blob/485b0316404a788416d5c953764deb21aa59b375/process_pr.py#L68) would allow a malicious user to inject whatever code that would be run on the testing machine. For example, an argument like:

` --what pippo; rm -fr *`

**Comment by silviodonato** [comment]
Thanks Marco. I started a dummy test in https://github.com/cms-sw/cmssw/pull/33490

**Comment by smuzaffar** [comment]
@rovere , thanks for taking the time to look in to this. Yes I know this but this check is only valid for cms authenticated users e.g see 
https://github.com/cms-sw/cms-bot/blob/485b0316404a788416d5c953764deb21aa59b375/process_pr.py#L589 
https://github.com/cms-sw/cms-bot/blob/485b0316404a788416d5c953764deb21aa59b375/process_pr.py#L672

so we trust our valid users to not abuse it. The valid users have many options to abuse the system e.g. make a CMSSW PR with a unit test to delete every thing :-)

**Comment by silviodonato** [comment]
Let me just add that the issue is real (see https://cmssdt.cern.ch/jenkins/job/ib-run-pr-relvals/3747/consoleFull ).

> The valid users have many options to abuse the system e.g. make a CMSSW PR with a unit test to delete every thing :-)

Interesting :-)

**Comment by dpiparo** [comment]
I wonder if we could put some fences, e.g. in Python you would use
```
subprocess.run(myCommand, shell=False,)
```
Maybe adjusting the regex and protecting against malicious execution on the target machine?

**Comment by apfeiffer1** [comment]
hmm ... two simple (simplistic??) suggestions:

a) replace RELVAL_OPTS="[a-zA-Z0-9_-][a-zA-Z0-9_-]*"  with RELVAL_OPTS="^[a-zA-Z0-9_-][a-zA-Z0-9_-]*$" if you want the options to _only_ contain alpha-numerics ... that would render any option with a ";" (and/or any other char) as failing the match.

b) simply replace any ";" in the options with "#"  (that would need the options to be the last item when assembling the command as anything after the options will be ignored.

**Comment by smuzaffar** [comment]
@dpiparo , I can update the regexp to be `^[-]{1,2}[a-zA-Z0-9_.,\s-]+` (note, we need to allow `[,.]` ). This will not allow to pass `;` or any quotes. But as I wrote the risk is always there as any one who is allowed to start a PR test can make a PR with a unit test to run any thing he/she wants.

**Comment by smuzaffar** [comment]
see https://github.com/cms-sw/cms-bot/pull/1541

**Comment by smuzaffar** [comment]
#1541 is merged now and cms-bot now does not allow `;` in the relval_opts ( see https://github.com/cms-sw/cmssw/pull/33490#issuecomment-824757185 where bot has thumbs down the comment with invalid opts). But as I said, there risk is still there. Only option to avoid this risk is that we only allow release managers to start tests and add test parameters but that is not practical

**Comment by dpiparo** [comment]
This is the reason why our integration flow foresees review of the code before it's merged, right?

**Comment by smuzaffar** [comment]
yes but I am not sure if it is reviewed thoroughly before requesting the tests to start :-)

**Comment by smuzaffar** [comment]
#1541 fixes this
