### ISSUE TITLE
bot / github UI get confused if the same branch is used for multiple PRs

### ISSUE THREAD

**Issue by jpata** [cms-sw/cms-bot#1605]
See e.g. the picture below, which is for https://github.com/cms-sw/cmssw/pull/34713, but includes messages also for https://github.com/cms-sw/cmssw/pull/34743. As @perrotta pointed out, both PRs use the same branch (this happens every once in a while). This means that the last "+1" and the github test status are not in sync, which can be confusing.

<img width="799" alt="Screenshot 2021-08-03 at 19 14 14" src="https://user-images.githubusercontent.com/69717/128050022-e3fbfea6-0db5-4adc-87d1-0902ed267bc7.png">

**Comment by smuzaffar** [comment]
@jpata  this is known issue. The github statuses (which you see at the end of PR) belongs to the actual commit. So if same commit is used for multiple PRs then github is going to show that status in all  PRs. To avoid bot setting the final "test-approved/rejected" status , we use PR number in the status (e.g. cms/34743 and cms/34713). So once all the statuses for PR 34743 have result then bot is going to update only 34743 labels.

**Comment by smuzaffar** [comment]
closing it as this is not in our control. This is feature of github itself
