### ISSUE TITLE
patching command

### ISSUE THREAD

**Issue by vlimant** [cms-sw/cms-bot#1820]
as per this comment https://github.com/cms-sw/cmssw/pull/38948#issuecomment-1205192983  from @smuzaffar it should be possible to have a gitbot command to apply a patch

**Comment by smuzaffar** [comment]
@vlimant thanks for opening the issue. https://github.com/cms-sw/cms-bot/pull/1821 change should now allow to run code-checks plus apply the changes.

When you open a PR for cmssw master branch then bot automatically run the code-checks. In case you want bot to automatically apply the code formatting changes then you can add `code-checks and apply patch` comment
