### ISSUE TITLE
Integrate part of NANO test in cmsbot commands

### ISSUE THREAD

**Issue by vlimant** [cms-sw/cms-bot#1823]
I am opening this issue to collect advice on how to best integrate some of the tests that are ran by xpog as part of the integration of NANO release. There is a gitlab workflow (that I learning the rope of ATM) https://gitlab.cern.ch/cms-nanoAOD/nanoAOD-integration/-/blob/master/.gitlab-ci.yml and it seems that 90% of it is a duplicate/repcursor of what cmsbot is doing with PR, with a NANOAOD cherry on top. 
As part of cleaning legacy tests, I think it would be beneficial to include most tests under cmsbot.

**Comment by smuzaffar** [comment]
closing this one in favor of cms-sw/cmssw#39452
