### ISSUE TITLE
Use cvmfs parallel publishers/gateway to deploy CMSSW IBs

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cms-bot#1850]

**Comment by smuzaffar** [comment]
Two test publisher and one gateway has been set by CERN IT to test this.

**Comment by smuzaffar** [comment]
FYI @jblomer @aandvalenzuela @iarspider 
@jblomer , if we get a lease for `/somepath` then can we still update `/.cvmfsdirtab` or cvmfs is going to ignore  `/.cvmfsdirtab` changes?

**Comment by jblomer** [comment]
It's true that on the publisher nothing prevents you from editing files outside your lease. But you won't be able to publish these changes.

**Comment by smuzaffar** [comment]
@jblomer , can we have .cvmfsdirtab under sub-directories e.g. can we have
- /cvmfs/repo.cern.ch/x86_64/.cvmfsdirtab
- /cvmfs/repo.cern.ch/aarch64/.cvmfsdirtab
- /cvmfs/repo.cern.ch/ppc64le/.cvmfsdirtab

**Comment by smuzaffar** [comment]
@jblomer @HereThereBeDragons , I see that cvmfs api for lease returns `key_id` [a] and looks like this is read from `/etc/cvmfs/keys/repo.gw` file. Can each publisher use a different key? I tired changing `/etc/cvmfs/keys/repo.gw`  file but then transaction failed 
```
> cvmfs_server transaction reponame/sw/x86_64
Error: 'invalid_hmac'
(unexpected termination) cannot parse session token
```

[a]
```
{"data":{"reponame/sw/x86_64":{"key_id":"key","path":"reponame/sw/x86_64","expires":"2022-10-31 14:02:53.2 +0100 CET"}},"status":"ok"}
```

**Comment by smuzaffar** [comment]
@jblomer @HereThereBeDragons  can you please also answer https://github.com/cms-sw/cms-bot/issues/1850#issuecomment-1293517758 ? Can we create `.cvmfsdirtab` in sub-directories or it only works for top level directory?

**Comment by smuzaffar** [comment]
@jblomer @HereThereBeDragons , actually no need to have separate key_ids for each publisher. The session token is enough to find out the open transaction.

By the way, is there any way to set the lease time at the time of transaction? There are some transactions ( specially when running under `qemu`) which can take more than 2 hours ( which is default `max_lease_time`) and it would we nice if one can set the lease time with `cvmfs_server transaction` command

**Comment by smuzaffar** [comment]
@jblomer  @HereThereBeDragons, when running `gc` on gateway, I get this error [a]. does this mean `gc` failed?

[a]
```
> cvmfs_server gc -f
Affected Repositories:         cms-ib-test.cern.ch
Dry Run (no actual deletion):  no
Needs Reflog reconstruction:   no
Preserve Revisions newer than: 10/29/22 11:12:42
Running Garbage Collection 
  --> marking unreferenced objects [Tue, 01 Nov 2022 09:12:43 GMT]
  --> sweeping unreferenced objects [Tue, 01 Nov 2022 09:15:25 GMT]
      - 10%    33 / 322 unreferenced revisions removed [Tue, 01 Nov 2022 09:15:27 GMT]
      - 20%    66 / 322 unreferenced revisions removed [Tue, 01 Nov 2022 09:16:10 GMT]
      - 31%    99 / 322 unreferenced revisions removed [Tue, 01 Nov 2022 09:16:11 GMT]
      - 41%    132 / 322 unreferenced revisions removed [Tue, 01 Nov 2022 09:16:11 GMT]
      - 51%    165 / 322 unreferenced revisions removed [Tue, 01 Nov 2022 09:16:12 GMT]
      - 61%    198 / 322 unreferenced revisions removed [Tue, 01 Nov 2022 09:16:13 GMT]
      - 72%    231 / 322 unreferenced revisions removed [Tue, 01 Nov 2022 09:16:24 GMT]
      - 82%    264 / 322 unreferenced revisions removed [Tue, 01 Nov 2022 09:16:35 GMT]
      - 92%    297 / 322 unreferenced revisions removed [Tue, 01 Nov 2022 09:18:36 GMT]
  --> done garbage collecting [Tue, 01 Nov 2022 09:18:36 GMT]
Statistics stored at: /var/spool/cvmfs/cms-ib-test.cern.ch/stats.db
find: '/var/spool/cvmfs/cms-ib-test.cern.ch/tmp/receiver': Permission denied
```

**Comment by jblomer** [comment]
> @jblomer , can we have .cvmfsdirtab under sub-directories e.g. can we have

Currently that's not possible, unfortunately. Only the .cvmfsdirtab file in the root directory is parsed.

**Comment by jblomer** [comment]
> @jblomer @HereThereBeDragons , I see that cvmfs api for lease returns `key_id` [a] and looks like this is read from `/etc/cvmfs/keys/repo.gw` file. Can each publisher use a different key? I tired changing `/etc/cvmfs/keys/repo.gw` file but then transaction failed

Yes, that is possible.  You need to use the single-file configuration mechanism in a single file as described here: 
https://cvmfs.readthedocs.io/en/stable/cpt-repository-gateway.html#advanced-repository-configuration

See also #3071

**Comment by jblomer** [comment]
> @jblomer @HereThereBeDragons, when running `gc` on gateway, I get this error [a]. does this mean `gc` failed?

GC itself worked. The error is nevertheless unexpected. Could you ask IT to give us root access to the gateway so that I can investigate?

**Comment by jblomer** [comment]
> @jblomer @HereThereBeDragons , actually no need to have separate key_ids for each publisher. The session token is enough to find out the open transaction.
> 
> By the way, is there any way to set the lease time at the time of transaction? There are some transactions ( specially when running under `qemu`) which can take more than 2 hours ( which is default `max_lease_time`) and it would we nice if one can set the lease time with `cvmfs_server transaction` command

Currently you cannot set the lease time on a transaction basis. Every transaction gets the lease time configured in the gateway. But you can increase that duration in the gateway. If a transaction returns earlier, the lease is immediately released.

**Comment by smuzaffar** [comment]
> https://cvmfs.readthedocs.io/en/stable/cpt-repository-gateway.html#advanced-repository-configuration

isn't it for keys restricting subpaths OR can I have multiple keys for same path e.g.
```
      "keys": [
        {
          "id": "keyid1",
          "path": "/"
        },
        {
          "id": "keyid2",
          "path": "/"
        }
      ]
```

**Comment by smuzaffar** [comment]
> Currently you cannot set the lease time on a transaction basis. Every transaction gets the lease time configured in the gateway. But you can increase that duration in the gateway. If a transaction returns earlier, the lease is immediately released.

Problem is that there are some transactions which should not take more than few secs and some can take couple of hours. If a small publish job on `publisher A` (with lease for `/PATH`) fails ( e.g. jenkins lost the connection or some other glitch) then it leaves the transaction open. Now if another job starts on different `publisher B` and try to get the lease for `/PATH`  then it has to wait for `max_lease_time` secs. Allowing to set the lease time at the time of transactions will allow to release the lease in short time.

**Comment by jblomer** [comment]
> isn't it for keys restricting subpaths OR can I have multiple keys for same path e.g.
> 
> ```
>       "keys": [
>         {
>           "id": "keyid1",
>           "path": "/"
>         },
>         {
>           "id": "keyid2",
>           "path": "/"
>         }
>       ]
> ```

Different keys for the same path should be fine.

**Comment by smuzaffar** [comment]
@jblomer , is there any cvmfs build-in env variable which points to current `$(uname -m)` ? I would like to use it to dynamically set the symlink `/cvmfs/cms-ib.cern.ch/lastet` pointing to

- on `aarch64` -> `/cvmfs/cms-ib.cern.ch/sw/aarch64/lastet`
- on `ppc64le` -> `/cvmfs/cms-ib.cern.ch/sw/ppc64le/lastet`
- on `x86_64` -> `/cvmfs/cms-ib.cern.ch/sw/x86_64/lastet`

**Comment by jblomer** [comment]
That would be actually nice, like AFS's arch. There is currently nothing built-in.  We can add it for future versions of cvmfs.  In the meantime, if you set one yourself we can distribute it through the config repositories.

**Comment by jblomer** [comment]
This [PR](https://github.com/cvmfs/cvmfs/pull/3127) makes CVMFS_ARCH available for use in variant symlinks.  I still have to check if/how we can make it part of the config repo to support current and older client versions.

Looking now into the Gateway lease API.

**Comment by jblomer** [comment]
And here is the PR for adding the publisher hostname to the lease: https://github.com/cvmfs/cvmfs/pull/3130

**Comment by smuzaffar** [comment]
closing this issue, we have been publishing in parallel for a long time now and things are very stable now
