### ISSUE TITLE
Workflow `39634.21` undefined in `igprof` 12_6_X

### ISSUE THREAD

**Issue by aandvalenzuela** [cms-sw/cms-bot#1854]
Hello,

We are having some failures in `igprof` jobs due to workflow `39634.21` not defined: 
```
05:29:28   File "/tmp/cmsbuild/jenkins/workspace/ib-run-igprof/CMSSW_12_6_X_2022-10-12-2300/bin/el8_amd64_gcc10/runTheMatrix.py", line 606, in <module>
05:29:28     ret = runSelected(opt)
05:29:28   File "/tmp/cmsbuild/jenkins/workspace/ib-run-igprof/CMSSW_12_6_X_2022-10-12-2300/bin/el8_amd64_gcc10/runTheMatrix.py", line 31, in runSelected
05:29:28     if len(undefSet)>0: raise ValueError('Undefined workflows: '+', '.join(map(str,list(undefSet))))
05:29:28 ValueError: Undefined workflows: 39634.21
05:29:28 ++ ls -d '39634.21*'
05:29:28 ls: cannot access '39634.21*': No such file or directory
05:29:28 + mv runTheMatrix.log
05:29:28 mv: missing destination file operand after 'runTheMatrix.log'
05:29:28 Try 'mv --help' for more information.
05:29:28 + ERR=1
05:29:28 + false
05:29:28 + exit 1
05:29:28 + ERR=1
```
See complete stack trace: https://cmssdt.cern.ch/jenkins/job/ib-run-igprof/37997/console
Failures appear only in in `CMSSW_12_6_X`. Could this be related with the clean-up of workflows performed in `12_6_X`?

I also see that this workflow has been hardcoded in [cms-cmpwg/profiling](https://github.com/cms-cmpwg/profiling/blob/master/Gen_tool/Gen.sh#L40). @gartung I see you are regularly taking care of this repository :) 

Could you please have a look?

Thank you,
Andrea.

**Comment by makortel** [comment]
> Could this be related with the clean-up of workflows performed in `12_6_X`?

I think this workflow is one of the phase2 workflows that were renumbered recently.  @srimanob could you confirm?

**Comment by srimanob** [comment]
39634.21 is prod workflow of PU ttbar with D88. The workflow id is reset. The new id for this is 21034.21.

**Comment by gartung** [comment]
The workflow for the Jenkins job is defined here
https://github.com/cms-sw/cms-bot/blob/5e40a1f65081f1832fcf9e16a851be68886bb378/cmssw-pr-test-config#L3
I can't modify that repo through the web interface.

**Comment by aandvalenzuela** [comment]
@srimanob, is the new wf id `21034.21` also valid for older release cycles (i.e. 12.4.X/12.5.X)?

**Comment by srimanob** [comment]
Nope. Only 12_6.

**Comment by srimanob** [comment]
By the way, @smuzaffar, should we update the wf for profiling?
https://github.com/cms-sw/cms-bot/blob/master/cmssw-pr-test-config#L3
