### ISSUE TITLE
Change default wfs for PR tests on GPU in `CMSSW_13_X_Y`

### ISSUE THREAD

**Issue by missirol** [cms-sw/cms-bot#1976]
https://github.com/cms-sw/cmssw/pull/41354 and https://github.com/cms-sw/cmssw/pull/41371 added GPU RelVals for 2023 conditions in `CMSSW_13_1_Y` and `CMSSW_13_0_X`, respectively.

I think that, ideally, PR tests on GPU should run by default

 - `12434.506,12434.512,12434.522` (2023 wfs) in `CMSSW_13_X_Y`, and
 - [`11634.506,11634.512,11634.522`](https://github.com/cms-sw/cms-bot/blob/555e3ead922f0730a7ae8dbbda39cee3fcdc6b34/cmssw-pr-test-config#L2) (2022 wfs) in earlier release cycles, which is what is already happening.

@fwyzard, what do you think?

@smuzaffar, would this be possible? (I don't know how `cmsbot` differentiates between release cycles)

**Comment by fwyzard** [comment]
We could replace `.506`, `.512`, `.522` with `.586`, that should run all three GPU workflows in a single job, and `.587`, which does the same but also runs a GPU-vs-CPU comparison.

In principle we could skip `.586`, but last time I checked I had the impression that `.587` did not run all the same DQM as `.586`, so for the time being it might be better to run both.

**Comment by missirol** [comment]
Okay, so we would have

 - `12434.586,12434.587` (2023 wfs) in `CMSSW_13_X_Y`, and
 - `11634.586,11634.587` (2022 wfs) in earlier release cycles.

**Comment by smuzaffar** [comment]
with https://github.com/cms-sw/cms-bot/pull/1977, bot should be able to select different relvals based on CMSSW version. We just need to add  some condition like the following in https://github.com/cms-sw/cms-bot/blob/df771f1f82512b8f34eb796891beae0c0bb5cdab/cmssw-pr-test-config . Once you have the right set of workflows for GPUs then either update here or open a cms-bot PR (once  https://github.com/cms-sw/cms-bot/pull/1977 is merged)
```
if CMSSW_version
  PR_TEST_MATRIX_EXTRAS_GPU=wf-set1
else
  PR_TEST_MATRIX_EXTRAS_GPU=wf-set2
fi
```

**Comment by missirol** [comment]
@smuzaffar, thanks. I think we can go with what is in https://github.com/cms-sw/cms-bot/issues/1976#issuecomment-1531148803.

I wrote something up, but it's probably wiser if I leave the implementation to you.
```bash
if [ $(echo "${CMSSW_VERSION}" | awk -F 'CMSSW_|_' '{print $2}') -ge 13 ]; then
  PR_TEST_MATRIX_EXTRAS_GPU=12434.586,12434.587
else
  PR_TEST_MATRIX_EXTRAS_GPU=11634.586,11634.587
fi
```

**Comment by missirol** [comment]
Thanks @smuzaffar !
