### ISSUE TITLE
New PR label for HLT integration

### ISSUE THREAD

**Issue by antoniovilela** [cms-sw/cms-bot#2192]
@makortel @iarspider @aandvalenzuela 

I was wondering if it would be possible to add a label, e.g. "hlt-int", to be added with "type hlt-int" or analogous to a PR.

This would identify work needed for HLT development&integration prior to a data taking period. This is characterized by development performed on top of the production release that needs a faster integration time than other updates to the production branch.

Thanks.

**Comment by makortel** [comment]
I have a few questions just to understand the situation better:

Is the current `urgent` label not good enough? (e.g. "too much" other stuff gets labeled with `urgent`)

Is the "HLT development&integration prior to a data taking period" the only use case that would need to be marked differently from `urgent` for the "faster integration time"? What about PRs like fixes for crashes in HLT or Tier0? Are existing labels (e.g. combination of `urgent` and `bug-fix`) sufficient for those?

(I don't object, but maybe a spelling out `hlt-integration` would be better. We could also add a `type hlt-int` shorthand command.)

**Comment by antoniovilela** [comment]
> I have a few questions just to understand the situation better:
> 
> Is the current `urgent` label not good enough? (e.g. "too much" other stuff gets labeled with `urgent`)
> 
> Is the "HLT development&integration prior to a data taking period" the only use case that would need to be marked differently from `urgent` for the "faster integration time"? What about PRs like fixes for crashes in HLT or Tier0? Are existing labels (e.g. combination of `urgent` and `bug-fix`) sufficient for those?
> 
> (I don't object, but maybe a spelling out `hlt-integration` would be better. We could also add a `type hlt-int` shorthand command.)

It seems "urgent" is subjective for this use case. There have been cases where they were not marked urgent but they expected a short turnaround in any case. Type "hlt-integration" would mark this somewhat exceptional HLT development cycle.

For fixing crashes during data taking, the PRs should be marked as urgent, and ORM should be contacted. We would then also bypass the requirement of ORP approval (as drafted in https://github.com/cms-sw/cmssw/issues/44283).  

"hlt-integration" with the "hlt-int" shorthand sounds great.  

Thanks again.

@cms-sw/hlt-l2

**Comment by mmusich** [comment]
> There have been cases where they were not marked urgent but they expected a short turnaround in any case

This is indeed why we have been reluctant to mark these development PR (essentially menu dumps) as "urgent". They are at a different (lower) level of urgency with respect to a fix for a HLT or Tier0 crash, but still we are working on a schedule to deliver the menu in time to allow deployment and testing so they should not lag too far behind.
Additionally to this, there is sometimes urgency in integrating reconstruction developments that directly impinge on the HLT schedule (see `alpaka` bug-fix or `fillDescriptions` fixes that affect confDB parsing).
Let me tag also @missirol (apologies I don't know Silvia's github user).

**Comment by missirol** [comment]
@goys

**Comment by makortel** [comment]
So if I understood correctly, the `hlt-integration` would be less urgent than `urgent` (*), but urgent-enough to require special attention from ORP?

(*) depending of course how `urgent` is used in practice

**Comment by antoniovilela** [comment]
> So if I understood correctly, the `hlt-integration` would be less urgent than `urgent` (*), but urgent-enough to require special attention from ORP?
> 
> (*) depending of course how `urgent` is used in practice

I would not specify the level of urgency here.

This is simply to help categorize this class of PRs. In practice, it will be useful in order to focus on these PRs, especially during certain periods.

These PRs can eventually also be marked as urgent, on top of this hlt-integration category.

This category will be included in the guidelines, which is however broader than what is being discussed in this particular issue.

Thanks.

@cms-sw/orp-l2

**Comment by makortel** [comment]
Ok, let's add the `hlt-integration` type label, with `type hlt-int` shorthand. I leave it to @smuzaffar @iarspider @aandvalenzuela to figure out who will do the changes.

**Comment by mmusich** [comment]
tangentially related to this thread I took the liberty of opening https://github.com/cms-sw/cms-sw.github.io/pull/118, this might help developers to produce code that can be directly used in HLT configurations.

**Comment by antoniovilela** [comment]
@smuzaffar @aandvalenzuela @iarspider
All ok to add this label?
Thanks.

**Comment by smuzaffar** [comment]
@antoniovilela , yes all ok. I will open a PR now

**Comment by antoniovilela** [comment]
> @antoniovilela , yes all ok. I will open a PR now

Thanks.
