### ISSUE TITLE
add non-blocking labels when assigning issues by package

### ISSUE THREAD

**Issue by slava77** [cms-sw/cms-bot#2248]
`assign package Subsystem/Package` can be used to assign a blocking label to issues.

Please expand it to non-blocking labels (as defined in categories_map.py).

**Comment by iarspider** [comment]
Already implemented. The issue was someplace else .

**Comment by slava77** [comment]
> Already implemented. The issue was someplace else .

ah, I see an example now in https://github.com/cms-sw/cmssw/issues/43886#event-11728557183
Apparently a hiccup in the bot in a recent PR made me think the feature is not available.
