### ISSUE TITLE
RelMon threshold to report a difference

### ISSUE THREAD

**Issue by slava77** [cms-sw/cms-bot#313]
Could you please check the settings of the RelMon running in jenkins.
Why does it not display differences that are actually showing up in the logs.
The specific case in #7565 (comment)
can be used as a reference example.

**Comment by ktf** [comment]
@nclopezo did you look into this?

**Comment by nclopezo** [comment]
Hi,
It seems that it was a glitch (https://github.com/cms-sw/cmssw/pull/7565#issuecomment-73120840). If this is happening again I can check it.

**Comment by slava77** [comment]
Hi David,

I'm not sure what was a glitch.
The state of RelMon is still the same, at least as of 2 days ago.

Since DAS is now a good generator of large differences in 140.53
I can use it as an example of missing differences in RelMon in 8752
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_7_4_X_2015-04-15-1100+8752/7174/

RelMon result has essentially no differences
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_7_4_X_2015-04-15-1100+8752/7174/140.53_RunHI2011+RunHI2011+RECOHID11+HARVESTDHI/
compare this to the slew of changes in the log file of RelMon (180MB log
file, you can dare to open)

vs
e.g. fwlite pt of tracks
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_7_4_X_2015-04-15-1100+8752/7174/validateJR/all_OldVSNew_RunHI2011wf140p53/all_OldVSNew_RunHI2011wf140p53c_log10recoTracks_hiGeneralTracks__reRECO_obj_pt.png

		--slava


On 4/17/15 3:16 AM, David Mendez wrote:
> Hi,
> It seems that it was a glitch (cms-sw/cmssw#7565 (comment)
> <https://github.com/cms-sw/cmssw/pull/7565#issuecomment-73120840>). If
> this is happening again I can check it.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-sw/cms-bot/issues/313#issuecomment-93940711>.
> 

-- 
***********************************************************************
 Vyacheslav (Slava) Krutelyov
 TAMU: Physics Dept Texas A&M MS4242, College Station, TX 77843-4242
 CERN: 42-R-027
 AIM/Skype: siava16              googleTalk: slava77@gmail.com
 (630) 291-5128  Cell (US)       +41 76 275 7116 Cell (CERN)

-----------------------------------------------------------------------

**Comment by slava77** [comment]
(I can't reopen an issue closed by an admin)

**Comment by nclopezo** [comment]
Hi Slava,

I modified the threshold to be 0.05, here are the results:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_7_4_X_2015-04-15-1100+8752/7242/140.53_RunHI2011+RunHI2011+RECOHID11+HARVESTDHI/
Are these results better? I can try with other values if you want.

**Comment by slava77** [comment]
Hi David,

As a check, could you please generate a diff with 0.005 as a threshold.
In majority of the cases of tests in jenkins we expect no changes at all,
since we are usually rerunning on the same events.
In this test case, where files are different, the number of failed
comparisons is still fairly small.
So, a looser selection would make sense.

(recall that for  the alternative-comparisons we applied some logic of
changing
thresholds in diffs depending on how many are found; it's unclear if the
same can be applied here as well)



On 4/21/15 6:21 AM, David Mendez wrote:
> Hi Slava,
> 
> I modified the threshold to be 0.05, here are the results:
> https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_7_4_X_2015-04-15-1100+8752/7242/140.53_RunHI2011+RunHI2011+RECOHID11+HARVESTDHI/
> Are these results better? I can try with other values if you want.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-sw/cms-bot/issues/313#issuecomment-94752261>.
> 

-- 
***********************************************************************
 Vyacheslav (Slava) Krutelyov
 TAMU: Physics Dept Texas A&M MS4242, College Station, TX 77843-4242
 CERN: 42-R-027
 AIM/Skype: siava16              googleTalk: slava77@gmail.com
 (630) 291-5128  Cell (US)       +41 76 275 7116 Cell (CERN)

-----------------------------------------------------------------------

**Comment by nclopezo** [comment]
Here are the results with 0.005
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_7_4_X_2015-04-15-1100+8752/20/

If I modify it to run first the JR comparison, the thresholds could be assigned in a similar way as for example: https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_7_4_X_2015-04-15-1100+8752/7174/alternative-comparisons/assignedParameters.log

**Comment by slava77** [comment]
On 4/21/15 8:23 AM, David Mendez wrote:
> Here are the results with 0.005
> https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_7_4_X_2015-04-15-1100+8752/20/


Sorry,  I misunderstood the direction of the threshold.
It's actually showing differences less probable that the threshold.
So, lets try 0.1 for this case with many differences
(this should be an equivalent of mod 2 in the alternative-comparisons).

The mapping to the choices done in alternative comparisons should be
- 0.999 for mod=3
- 0.1 for mod=2
- 0.999999999999 for mod=1
I'm not sure if there is a switch for mod=0 (any bin difference) in RelMon



> 
> If I modify it to run first the JR comparison, the thresholds could be
> assigned in a similar way as for example:
> https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_7_4_X_2015-04-15-1100+8752/7174/alternative-comparisons/assignedParameters.log
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cms-sw/cms-bot/issues/313#issuecomment-94792655>.
> 

-- 
***********************************************************************
 Vyacheslav (Slava) Krutelyov
 TAMU: Physics Dept Texas A&M MS4242, College Station, TX 77843-4242
 CERN: 42-R-027
 AIM/Skype: siava16              googleTalk: slava77@gmail.com
 (630) 291-5128  Cell (US)       +41 76 275 7116 Cell (CERN)

-----------------------------------------------------------------------

**Comment by nclopezo** [comment]
Right now it is like this: https://github.com/cms-sw/cms-bot/blob/master/comparisons/analyzeFWComparison.py#L65

I can do the same with the thresholds for RelMon comparisons

**Comment by slava77** [comment]
David, 
I think the same logic should work for RelMon.
Thank you.

**Comment by nclopezo** [comment]
Hi Slava, 
Here you can see the results with the dynamic assignment of thresholds:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_7_4_X_2015-04-15-1100+8752/38/
You can see in the file [RelMonAssignedParameters.log](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_7_4_X_2015-04-15-1100+8752/38/RelMonAssignedParameters.log) how the parameters were assigned. 
And in this [RelMonComparisonParams.txt](https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_7_4_X_2015-04-15-1100+8752/38/RelMonComparisonParams.txt) a summary of the thresholds which is used by the script when it launches the RelMon comparison.

**Comment by nclopezo** [comment]
If this is ok I will merge this new feature to the cms-bot master branch.

**Comment by nclopezo** [comment]
I merged it and it should now be available for the next comparisons.

**Comment by slava77** [comment]
thank you. 
Sorry, I couldn't check earlier.
Looking at the RelMonAssignedParameters.log , the chosen params make sense
