### ISSUE TITLE
notify after the IB tests are done if PR merge included more recent changes than the IB

### ISSUE THREAD

**Issue by slava77** [cms-sw/cms-bot#436]
I'm taking https://github.com/cms-sw/cmssw/pull/8653#issuecomment-95670597 as an example:
in a case when "(HEAD+PR merge ) vs HEAD " is not the same as "(IB+ PR merge) vs IB",
the PR integration tests actually test (redundantly) other changes that were merged after the IB used for tests was made.

Could you please add a note in the jenkins build report (the first message from ib-any-integration) posted in the thread that would tell that the tests include effects of more than just this PR code change as would be seen on top of the head.
This will be useful for the L2s checking the results.
Given this info, it's up to the person reviewing the results if a new test should be requested.

**Comment by nclopezo** [comment]
Hi Slava, 
I did it in https://github.com/cms-sw/cms-bot/pull/443
