### ISSUE TITLE
Request that jenkins listens to @lgray

### ISSUE THREAD

**Issue by lgray** [cms-sw/cms-bot#514]
Hi, 

I've been submitting a lot of PRs lately of varying complexity. 
It would be useful if I could submit Jenkins tests to ease the load on @slava77 and others.

Thanks,
-Lindsey

**Comment by slava77** [comment]
I don't think this would really help that much.

I'm OK with @lgray (and others at the level of POG/DPG contacts to be able to trigger the tests).

**Comment by slava77** [comment]
opening up the list shouldn't be used though as a way to use jenkins to run basic test of the PR code.
We need to evaluate if we have enough resources to do that.
Nominal steps imply that a developer has tested the PR in a latest IB (or, knowing all implications, in a pre-release).

**Comment by lgray** [comment]
That's not what I intend to do with it. I can facilitate the routine testing of backports once the PR is submitted (after checking locally), etc. Considering I am keeping track of 20 PRs for EGM at the moment it seemed somewhat useful.
