### ISSUE TITLE
Add me as watcher of alca category.

### ISSUE THREAD

**Issue by ghellwig** [cms-sw/cms-bot#657]
Could you please add me to the watchers of the packages in the alca category?

Does this clash with the list of packages I am anyway watching, i.e. will I get duplicated emails if I watch a package already in the alca category?

-Gregor

**Comment by smuzaffar** [comment]
Done here https://github.com/cms-sw/cms-bot/commit/0100fa89aa5ce7fc0dcf755753407f0a3e3f0f08
No, you should not get duplicate emails

**Comment by ghellwig** [comment]
Thanks!
