### ISSUE TITLE
Add G. Mittag in the list of CMSSW_L2 (AlCa)

### ISSUE THREAD

**Issue by mmusich** [cms-sw/cms-bot#671]
Dear cms-bot managers,
please add Gregor Mittag (@ghellwig) to the list of L2s for AlCa. He's the current AlCa software coordinator.
Thanks,

attn.: @franzoni @cerminar

**Comment by iahmad-khan** [comment]
https://github.com/cms-sw/cms-bot/pull/672

**Comment by mmusich** [comment]
@iahmad-khan thanks
