### ISSUE TITLE
add/expand "test with " cms-bot command to also include cmssw PRs

### ISSUE THREAD

**Issue by slava77** [cms-sw/cms-bot#813]
this is possible manually via jenkins interface
So, why not extend this further.

**Comment by smuzaffar** [comment]
+1
I would also like to expand it to provide the extra workflows to be tested. Sometime a PR fixes a workflow which is not part of standard PR testing procedure. So how about something like 
```please test[ workflow WF[,WF]][ with[ #PR][ cms-sw/cmsdist#<PR>]]```
e.g.
```
please test with #123
please test with #123 cms-sw/cmsdist#789
please test workflow 1.0
please test workflow 1.0,1000.0 with #123
```

**Comment by slava77** [comment]
On 3/3/17 9:06 AM, Malik Shahzad Muzaffar wrote:
> +1
> I would also like to expand it to provide the extra workflows to be
> tested. Sometime a PR fixes a workflow which is not part of standard PR
> testing procedure. So how about something like
> |please test[ workflow WF[,WF]][ with[ #PR][ cms-sw/cmsdist#<PR>]]|
> e.g.
> 
> |please test with #123 please test with #123 cms-sw/cmsdist#789 please
> test workflow 1.0 please test workflow 1.0,1000.0 with #123 |
> 

this is even better.


I'd eventually want to ask to extend the functionality to run some
pre-packaged set of tests
extended over the short matrix (-s or -l limited) with varying
non-default number of events in each,
more events.
E.g. 10224 100 events; 10021 500 events.
We run these occasionally manually, but some more automation may be useful.

**Comment by slava77** [comment]
On 3/3/17 9:06 AM, Malik Shahzad Muzaffar wrote:
> +1
> I would also like to expand it to provide the extra workflows to be
> tested. Sometime a PR fixes a workflow which is not part of standard PR
> testing procedure. So how about something like
> |please test[ workflow WF[,WF]][ with[ #PR][ cms-sw/cmsdist#<PR>]]|
> e.g.
> 
> |please test with #123 please test with #123 cms-sw/cmsdist#789 please


> test workflow 1.0 please test workflow 1.0,1000.0 with #123 |

One thing that complicates this a bit is that the baseline should be
triggered as well
by this request if it's not made already and then wait for that to
complete to do comparisons.
Else, this will be just limited to a check that the extra workflow runs

**Comment by smuzaffar** [comment]
cms-bot should now be able to recognize the following 
```
- please test
  Normal Pr testing
- please test workflow <workflows>
  Test PR with extra runTheMatrix workflows
  <workflows> is comma separated list of runTheMatrix workflows e.g. 1.0,202.0
- please test with <#cmssw-prs>
  test PR with extra CMSSW PRS
  <cmssw-prs> is comma separated list of cmssw PRs e.g #17567,#17434
- please test with cms-sw/cmsdist#PR
  test PR with an extra cmsdist PR
- please test with <#cmssw-prs>  cms-sw/cmsdist#PR
  test with an extra cmsdist PR and one or more cmssw PRs
- please test workflow <workflows> with <#cmssw-prs>  cms-sw/cmsdist#PR
  test extra workflows with extra cmssw PRs and an extra cmsdist PR
```

The idea of testing extra workflows (which are not part of normal testing) is that most of the time a PR fixes a workflow which is failing in the IB. So there is no use of running a baseline for those workflows.

**Comment by smuzaffar** [comment]
this is done. Open a new issue if this this is not behaving correctly.
