### ISSUE TITLE
BTV-dedicated github labels

### ISSUE THREAD

**Issue by mverzett** [cms-sw/cms-bot#851]
Dear experts,

I am considering if it would be beneficial for our (BTV) internal bookkeeping of the PRs to have a dedicated github label in cmssw. The idea would be that any of our developers, at the moment of creating a PR, would trigger the CMS bot to add such label and, in case for some reason we would not be notified, the conveners and RECO contacts of the group would be added in the watchers list.

Is such thing possible?

Thanks

Mauro

**Comment by mverzett** [comment]
@ferencek will be interested to follow the discussion

**Comment by slava77** [comment]
On 5/18/17 7:18 AM, Mauro Verzetti wrote:
> Dear experts,
> 
> I am considering if it would be beneficial for our (BTV) internal
> bookkeeping of the PRs to have a dedicated github label in cmssw. The
> idea would be that any of our developers, at the moment of creating a
> PR, would trigger the CMS bot to add such label and, in case for some
> reason we would not be notified, the conveners and RECO contacts of the
> group would be added in the watchers list.
> 
> Is such thing possible?

Is this needed for the BTV community to be able to search for such PRs?
Current way for developers or interested to know of relevant PRs is to
be a watcher.

**Comment by mverzett** [comment]
@slava77 , 
"Is this needed for the BTV community to be able to search for such PRs?"
yeah, that's the idea, so we can easily keep track of the PR status inside the BTV. 

All the interested people are already watchers if the important packages, but sometimes it happened that some BTV related PR (I'm think about the track truth) might slip under the radar given they affect packages we do not touch very frequently.

**Comment by slava77** [comment]
On 5/18/17 7:44 AM, Mauro Verzetti wrote:
> @slava77 <https://github.com/slava77> ,
> "Is this needed for the BTV community to be able to search for such PRs?"
> yeah, that's the idea, so we can easily keep track of the PR status
> inside the BTV.
> 
> All the interested people are already watchers if the important
> packages, but sometimes it happened that some BTV related PR (I'm think
> about the track truth) might slip under the radar given they affect
> packages we do not touch very frequently.
> 

You could add cms-btv-pog to the list of watchers  or have relevant
github users add @cms-btv-pog and search by that
Would it work?

**Comment by ferencek** [comment]
@mverzett, as long as a package is listed under `btv-pog` in https://github.com/cms-sw/cms-bot/blob/master/watchers.yaml the people belonging to that group (defined in https://github.com/cms-sw/cms-bot/blob/master/groups.yaml) will be notified. It is indeed possible that something slips under the radar if it is a change in a package not included in the watch list that still directly or indirectly affects b tagging. However, wouldn't this label thing critically depend on developers being familiar with the procedure and disciplined enough to added the right keyword to trigger the CMS bot? That does not look very robust to me.

What @slava77 proposes would actually achieve the same thing (except a developer team, such as @cms-btv-pog/cmssw-developers, not organization, needs to be mentioned) but again assuming that PR creators will follow the guidelines.
