### ISSUE TITLE
cms-bot is ignoring some merge requests recently

### ISSUE THREAD

**Issue by davidlange6** [cms-sw/cms-bot#924]
hi @smuzaffar - I notice several occurrences where the bot seems to ignore a PR eg

https://github.com/cms-sw/cmssw/pull/21586

**Comment by smuzaffar** [comment]
bot did try to merge it but looks like it fail due to some unknow error (as error was ignored). I have updated bot to fail the jenkins job if it failed to merge ( https://github.com/cms-sw/cms-bot/commit/5c1775306adfd51fe8d64ca9799970de12b41256#diff-0a7e523386c241be1a6445a4901aef6c )
