### ISSUE TITLE
Update new package message

### ISSUE THREAD

**Issue by kpedro88** [cms-sw/cms-bot#927]
https://github.com/cms-sw/cms-bot/blob/433d47e4db47afebd4648b98ef9e42d4e9d1b118/process_pr.py#L268

should now point to `categories_map.py`

**Comment by smuzaffar** [comment]
thanks @kpedro88 for pointing this out. https://github.com/cms-sw/cms-bot/commit/56b33b9b4fde7339da1ee7d3712545fed4cee826 should fix this
