### ISSUE TITLE
false-positives in cms-bot "The following merge commits were also included on top of IB"

### ISSUE THREAD

**Issue by slava77** [cms-sw/cms-bot#930]
It looks like the detection of the last additional merge is failing and reports the last merge from an IB no matter what

One example is https://github.com/cms-sw/cmssw/pull/21708
```
Tested at: c0ff3a9

The following merge commits were also included on top of IB + this PR after doing git cms-merge-topic:
a4f36f2
```
- The commit a4f36f2 is the same as the last commit in CMSSW_10_0_X_2017-12-13-2300, which is used to run the tests. It should not be reported as a commit also included on top of IB.

**Comment by smuzaffar** [comment]
@slava77 , as we are now using exact time of release tag that is why we get two commit (one for release and one for the PR). https://github.com/cms-sw/cms-bot/commit/354fde943d6cc6372b48821198618b374d80a390 should fix this.

**Comment by slava77** [comment]
On 12/14/17 9:44 AM, Malik Shahzad Muzaffar wrote:
> @slava77 <https://github.com/slava77> , as we are now using exact time
> of release tag that is why we get two commit (one for release and one
> for the PR). 354fde9
> <https://github.com/cms-sw/cms-bot/commit/354fde943d6cc6372b48821198618b374d80a390>
> should fix this.

Thank you for the quick update.

**Comment by slava77** [comment]
... but now I see that the change was redone in a different way more recently 6f7fb8b6c5ab6c66b76f6e7648bcdaff6695c3e8
which is perhaps even more straightforward.

**Comment by smuzaffar** [comment]
Yes, looks like https://github.com/cms-sw/cms-bot/commit/6f7fb8b6c5ab6c66b76f6e7648bcdaff6695c3e8 gives correct results e.g. I tested it for https://github.com/cms-sw/cmssw/pull/21723 and with old implementation I get
```
IB_DATE=$(git show CMSSW_10_0_X_2017-12-13-2300 --pretty=format:%ai)
git rev-list --after="$IB_DATE" HEAD --merges
02abb2442cc7330d1081f0a613a399a17255765a <--- merge commit for PR 21723
6136d621e26a5d702aa465e043230c5fcf7a66fa
c864dffbedb9292f36d6de03e3aa3a3ece4d736d
31b46aa2b70068f9405fc277c03116189048543d
e22dd6569933945c486e8272fde4e7c5e15a2b82
a4f36f26b092be8d42543d9bcf166711294af0ca  <---- Release tag commit
```
while with new changes it give
```
git rev-list CMSSW_10_0_X_2017-12-13-2300..HEAD --merges
02abb2442cc7330d1081f0a613a399a17255765a   <--- merge commit for PR 21723
6136d621e26a5d702aa465e043230c5fcf7a66fa
c864dffbedb9292f36d6de03e3aa3a3ece4d736d
31b46aa2b70068f9405fc277c03116189048543d
e22dd6569933945c486e8272fde4e7c5e15a2b82
```
