### ISSUE TITLE
Add @echabert as watcher of strip packages

### ISSUE THREAD

**Issue by echabert** [cms-sw/cms-bot#959]
Would you please add me (@echabert) as watcher of all the packages listed below ?
I'm co-covenor of the strip local reco & calib group with @mmusich 
Thanks in advance

- CalibTracker/Configuration
- CalibTracker/Records
- CalibTracker/SiStrip
- DataFormats/SiStrip
- DPGAnalysis/SiStripTools
- RecoLocalTracker/ClusterParameterEstimator
- RecoLocalTracker/Configuration
- RecoLocalTracker/Records
- RecoLocalTracker/SiStrip
- RecoLocalTracker/SubCollectionProducers
- SimTracker/Common
- SimTracker/Configuration
- SimTracker/Records
- SimTracker/SiStripDigitizer

**Comment by smuzaffar** [comment]
@echabert , sure. Please make a Pull request with the changes for https://github.com/cms-sw/cms-bot/blob/master/watchers.yaml .
