### ISSUE TITLE
relmon comparisons directory cleanup

### ISSUE THREAD

**Issue by slava77** [cms-sw/cms-bot#964]
This is a follow up to https://github.com/cms-sw/cmssw/pull/22531#issuecomment-373371950

I checked comparison files  avialable in /afs/cern.ch/work/m/muzaffar/public/PR22531.tar.gz

by the count, most files are in the relmon directories

e.g. 
./PR22531/25660/1000.0_RunMinBias2011A+RunMinBias2011A+TIER0+SKIMD+HARVESTDfst2+ALCASPLIT
28825 files

Almost all of it is taken up just by the html files that display navigation through all of the directories and in almost in all cases there is no useful information, they just show "success" in the comparisons.

I think that we can save a lot by dropping directories/htmls with only Success in the results for the (standard in cms-bot) setup of showing only differences.
Based on the output format, I think that only html files that match this pattern in the content ```"Skipped:\|Null:\|Fail:"``` should be kept. In the example with wf 1000.0 there are only 11 files with ```"Skipped:\|Null:\|Fail:"```. The rest can be dropped.

I'm not well familiar with the RelMon options. Perhaps this can be done already at the output creation step. If that's not really possible, then a simple sweeping script can be added to rm all files with just success in the comparisons.

**Comment by smuzaffar** [comment]
@slava77 , cms-bot changes https://github.com/cms-sw/cms-bot/commit/6327327f7e57a216b04d98db9cfa03ab767077f0 should allow to filter-out successful comparisons and keep only those which contain Skipped, Null or Failed.

For now this is disabled but can be enabled via jenkins job parameter. I did a dry run on PR 23520 comparisons and this is what it is going to look after the filtering
Original: https://cmssdt.cern.ch/SDT/jenkins-artifacts/baseLineComparisons/CMSSW_10_2_X_2018-06-06-2300+23520/26982/8.0_BeamHalo+BeamHalo+DIGICOS+RECOCOS+ALCABH+HARVESTCOS/
New: https://cmssdt.cern.ch/buildlogs/filtered/23520/8.0_BeamHalo+BeamHalo+DIGICOS+RECOCOS+ALCABH+HARVESTCOS/

For this PR numbers of files are reduced from 236K to just 268.
Note that links to successful comparison in new one will be broken. Also if a workflow is all clean then it directory will also be missing ( e.g. workflow 5.1 is missing in here https://cmssdt.cern.ch/buildlogs/filtered/23520/ ).

If this looks good then I can enable it for future PR comparison tests.

**Comment by fabiocos** [comment]
@smuzaffar concerning your last comment, in case of full success the comparison is not shown but the corresponding Matrix Output will still be accessible, that is not affected, right? 

I think this might save quite some space and avoid wasting time to search for places where differences appear. But before putting it in production people should be warend, to avoid they are surprised by the change

**Comment by smuzaffar** [comment]
@fabiocos , yes the matrix output (log file) and pickle files will still be available.

Should I open a cmssw issue mentioning all L2s about the change or send a hypernews message to sw-develtools?

**Comment by fabiocos** [comment]
@smuzaffar in case @slava77 is satisfied and others have no objection, I would go to an hn message, that is likely read by more people. The change will affect any developer at the end of the day

**Comment by slava77** [comment]
On 6/8/18 2:33 AM, Fabio Cossutti wrote:
> @smuzaffar <https://github.com/smuzaffar> in case @slava77
> <https://github.com/slava77> is satisfied and others have no objection,
> I would go to an hn message, that is likely read by more people. The
> change will affect any developer at the end of the day
> 
> —

It may be useful to add some text either next to the currently dead
links or actually put the files linked saying somthing like "There are
no changes in this directory, nothing to be shown or navigated to"

**Comment by smuzaffar** [comment]
This is now in active for PR comparison tests.
