### ISSUE TITLE
report compilation warnings in PR test summary

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cms-bot#990]
During a PR test, compilation warnings are visible by browsing the "Compilation" sub-page of the test output summary html, but unless this is directly inspected at any test they go unnoticed until the merge and the IB test. 

The https://github.com/cms-sw/cms-bot/blob/master/report-pull-request-results.py script checks and reports only build errors, as detected by the function read_build_log_file at https://github.com/cms-sw/cms-bot/blob/master/report-pull-request-results.py#L237

This function could be updated so as to report also possible warning messages, without breaking in that case the parsing of the file, but just adding to the output message the detection of one or more occurrences of the string "warning:"

**Comment by Dr15Jones** [comment]
assign core

**Comment by fabiocos** [comment]
@smuzaffar I could provide a suggestion, but I am not sure how to test it before its deployment

**Comment by fabiocos** [comment]
Alternatively, one could at least indicate the presence of warnings in the summary page, which means touching also https://github.com/cms-sw/cms-bot/blob/master/templates/js/renderPRTests.js

**Comment by smuzaffar** [comment]
@fabiocos , I am enabled the checking of warnings for PR tests. Basically I ran https://github.com/cms-sw/cms-bot/blob/master/buildLogAnalyzer.py script (which we run for Ibs) on PR logs to find out the warnings. For now, cms-bot will add in the PR results message the presence of warning or not. later I will update bot to add a `warning` label to PR so that one can quickly noticed it.

One question: If we hav compilation warnings then should run relval tests or not? Should be reject a PR if there are warnings?

**Comment by fabiocos** [comment]
@smuzaffar thank you a lot. I think that a warning is not in itself preventing the test (actually we discover some of them after merge), it should be more a helper tool for the scrutiny. Unless we want to force people to fix anyway the warning as a pre-condition, and treat it as a show-stopper. But this could be a bit extreme IMO

**Comment by smuzaffar** [comment]
OK, then I will just add a `warning` label to indicate that there are warnings.

**Comment by Dr15Jones** [comment]
I also vote for the warnings to not stop further testing.

**Comment by smuzaffar** [comment]
OK, for each PR now cms-bot should create a `compilation-warnings` label ( like this https://github.com/cms-sw/cmssw/pull/23468 ) and one can see the build logs from the summary page e.g. https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-23502/28516/summary.html

**Comment by slava77** [comment]
On 6/6/18 6:18 AM, Malik Shahzad Muzaffar wrote:
> OK, for each PR now cms-bot should create a |compilation-warnings| label
> ( like this cms-sw/cmssw#23468
> <https://github.com/cms-sw/cmssw/pull/23468> ) and one can see the build
> logs from the summary page e.g.
> https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-23502/28516/summary.html
> 

Hi Shahzad

Is there a hook to list to ignore known warnings in this setup?

**Comment by smuzaffar** [comment]
@slava77 , no, currently there is no hook to feed in the known warnings. But we can get the existing warnings from IB logs and ignore those for PR.

**Comment by smuzaffar** [comment]
By the way, if we ignore the known warnings (e.g. those which are in IB) then if a PR is suppose to fix a warning but actually did not fix it then bot will ignore that too.
